### ISSUE TITLE
Gamejolt: gulp watch

### ISSUE THREAD

**Issue by Qvernaut** [gamejolt/gamejolt#35]
```
qvernaut@Linux-Ubuntu:/var/www/gamejolt$ sudo gulp watch
[20:19:32] Using gulpfile /var/www/gamejolt/gulpfile.js
[20:19:32] Starting 'watch:start'...
[20:19:32] Starting 'default'...
[20:19:32] Starting 'clean:pre'...
[20:19:32] Finished 'clean:pre' after 250 ms
[20:19:32] Starting 'pre'...
[20:19:32] Finished 'pre' after 23 μs
[20:19:32] Starting 'styles:app'...
[20:19:33] Starting 'styles:extra'...
[20:19:33] Finished 'styles:extra' after 19 μs
[20:19:33] Starting 'html2js:tooltip'...
[20:19:33] Starting 'html2js:modal'...
[20:19:33] Starting 'html2js:auth:partials'...
[20:19:33] Starting 'html2js:app:partials'...
[20:19:33] Starting 'js:module:vendor-app.js'...
[20:19:33] 'js:module:vendor-app.js' errored after 1.64 ms
[20:19:33] Error: Cannot find module '../../../../../src/bower-lib/moment/.bower.json'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at getBowerComponentFiles (/var/www/gamejolt/src/lib/gj-lib-client/gulp/tasks/js.js:26:24)
    at /var/www/gamejolt/src/lib/gj-lib-client/gulp/tasks/js.js:330:31
    at arrayEach (/var/www/gamejolt/node_modules/lodash/index.js:1314:13)
    at Function.<anonymous> (/var/www/gamejolt/node_modules/lodash/index.js:3355:13)
    at Gulp.<anonymous> (/var/www/gamejolt/src/lib/gj-lib-client/gulp/tasks/js.js:328:8)
    at module.exports (/var/www/gamejolt/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
[20:19:33] 'watch:start' errored after 1.55 s
[20:19:33] Error: [object Object]
    at formatError (/usr/local/lib/node_modules/gulp/bin/gulp.js:169:10)
    at Gulp.<anonymous> (/usr/local/lib/node_modules/gulp/bin/gulp.js:195:15)
    at Gulp.EventEmitter.emit (events.js:117:20)
    at Gulp.Orchestrator._emitTaskDone (/var/www/gamejolt/node_modules/gulp/node_modules/orchestrator/index.js:264:8)
    at /var/www/gamejolt/node_modules/gulp/node_modules/orchestrator/index.js:275:23
    at finish (/var/www/gamejolt/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
    at cb (/var/www/gamejolt/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:29:3)
    at finish (/var/www/gamejolt/node_modules/run-sequence/index.js:38:5)
    at Gulp.onError (/var/www/gamejolt/node_modules/run-sequence/index.js:45:4)
    at Gulp.EventEmitter.emit (events.js:117:20)
[20:19:33] 'default' errored after 1.55 s
[20:19:33] Error: [object Object]
    at formatError (/usr/local/lib/node_modules/gulp/bin/gulp.js:169:10)
    at Gulp.<anonymous> (/usr/local/lib/node_modules/gulp/bin/gulp.js:195:15)
    at Gulp.EventEmitter.emit (events.js:117:20)
    at Gulp.Orchestrator._emitTaskDone (/var/www/gamejolt/node_modules/gulp/node_modules/orchestrator/index.js:264:8)
    at /var/www/gamejolt/node_modules/gulp/node_modules/orchestrator/index.js:275:23
    at finish (/var/www/gamejolt/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
    at cb (/var/www/gamejolt/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:29:3)
    at finish (/var/www/gamejolt/node_modules/run-sequence/index.js:38:5)
    at Gulp.onError (/var/www/gamejolt/node_modules/run-sequence/index.js:45:4)
    at Gulp.EventEmitter.emit (events.js:117:20)
[20:19:33] 'default' errored after 1.55 s
[20:19:33] Error: [object Object]
    at formatError (/usr/local/lib/node_modules/gulp/bin/gulp.js:169:10)
    at Gulp.<anonymous> (/usr/local/lib/node_modules/gulp/bin/gulp.js:195:15)
    at Gulp.EventEmitter.emit (events.js:117:20)
    at Gulp.Orchestrator._emitTaskDone (/var/www/gamejolt/node_modules/gulp/node_modules/orchestrator/index.js:264:8)
    at /var/www/gamejolt/node_modules/gulp/node_modules/orchestrator/index.js:275:23
    at finish (/var/www/gamejolt/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
    at cb (/var/www/gamejolt/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:29:3)
    at finish (/var/www/gamejolt/node_modules/run-sequence/index.js:38:5)
    at Gulp.onError (/var/www/gamejolt/node_modules/run-sequence/index.js:45:4)
    at Gulp.EventEmitter.emit (events.js:117:20)
{ lineno: 24,
  column: 33,
  filename: '/var/www/gamejolt/src/lib/gj-lib-client/stylus/common/index.styl',
  stylusStack: '',
  name: 'Error',
  message: '/var/www/gamejolt/src/lib/gj-lib-client/stylus/common/index.styl:24:33\n   20| @import \'./functions\'\n   21| \n   22| // Normalize\n   23| if ( !$gj-exclude-common-normalize )\n   24| \t@import $gj-bower-lib-folder + \'/bootstrap-stylus/stylus/normalize\'\n---------------------------------------^\n   25| \n   26| // Set up our global variables.\n   27| @import $gj-bower-lib-folder + \'/bootstrap-stylus/stylus/variables\'\n\nfailed to locate @import file ../../../../bower-lib/bootstrap-stylus/stylus/normalize.styl\n',
  stack: 'Error: /var/www/gamejolt/src/lib/gj-lib-client/stylus/common/index.styl:24:33\n   20| @import \'./functions\'\n   21| \n   22| // Normalize\n   23| if ( !$gj-exclude-common-normalize )\n   24| \t@import $gj-bower-lib-folder + \'/bootstrap-stylus/stylus/normalize\'\n---------------------------------------^\n   25| \n   26| // Set up our global variables.\n   27| @import $gj-bower-lib-folder + \'/bootstrap-stylus/stylus/variables\'\n\nfailed to locate @import file ../../../../bower-lib/bootstrap-stylus/stylus/normalize.styl\n\n    at Evaluator.visitImport (/var/www/gamejolt/node_modules/stylus/lib/visitor/evaluator.js:901:21)\n    at Evaluator.Visitor.visit (/var/www/gamejolt/node_modules/stylus/lib/visitor/index.js:28:40)\n    at Evaluator.visit (/var/www/gamejolt/node_modules/stylus/lib/visitor/evaluator.js:156:18)\n    at Evaluator.visitBlock (/var/www/gamejolt/node_modules/stylus/lib/visitor/evaluator.js:706:39)\n    at Evaluator.Visitor.visit (/var/www/gamejolt/node_modules/stylus/lib/visitor/index.js:28:40)\n    at Evaluator.visit (/var/www/gamejolt/node_modules/stylus/lib/visitor/evaluator.js:156:18)\n    at Evaluator.visitIf (/var/www/gamejolt/node_modules/stylus/lib/visitor/evaluator.js:789:18)\n    at Evaluator.Visitor.visit (/var/www/gamejolt/node_modules/stylus/lib/visitor/index.js:28:40)\n    at Evaluator.visit (/var/www/gamejolt/node_modules/stylus/lib/visitor/evaluator.js:156:18)\n    at Evaluator.visitBlock (/var/www/gamejolt/node_modules/stylus/lib/visitor/evaluator.js:706:39)',
  showStack: false,
  showProperties: true,
  plugin: 'gulp-stylus' }
[20:19:33] Finished 'styles:app' after 1.63 s
{ lineno: 24,
  column: 33,
  filename: '/var/www/gamejolt/src/lib/gj-lib-client/stylus/common/index.styl',
  stylusStack: '',
  name: 'Error',
  message: '/var/www/gamejolt/src/lib/gj-lib-client/stylus/common/index.styl:24:33\n   20| @import \'./functions\'\n   21| \n   22| // Normalize\n   23| if ( !$gj-exclude-common-normalize )\n   24| \t@import $gj-bower-lib-folder + \'/bootstrap-stylus/stylus/normalize\'\n---------------------------------------^\n   25| \n   26| // Set up our global variables.\n   27| @import $gj-bower-lib-folder + \'/bootstrap-stylus/stylus/variables\'\n\nfailed to locate @import file ../../../../bower-lib/bootstrap-stylus/stylus/normalize.styl\n',
  stack: 'Error: /var/www/gamejolt/src/lib/gj-lib-client/stylus/common/index.styl:24:33\n   20| @import \'./functions\'\n   21| \n   22| // Normalize\n   23| if ( !$gj-exclude-common-normalize )\n   24| \t@import $gj-bower-lib-folder + \'/bootstrap-stylus/stylus/normalize\'\n---------------------------------------^\n   25| \n   26| // Set up our global variables.\n   27| @import $gj-bower-lib-folder + \'/bootstrap-stylus/stylus/variables\'\n\nfailed to locate @import file ../../../../bower-lib/bootstrap-stylus/stylus/normalize.styl\n\n    at Evaluator.visitImport (/var/www/gamejolt/node_modules/stylus/lib/visitor/evaluator.js:901:21)\n    at Evaluator.Visitor.visit (/var/www/gamejolt/node_modules/stylus/lib/visitor/index.js:28:40)\n    at Evaluator.visit (/var/www/gamejolt/node_modules/stylus/lib/visitor/evaluator.js:156:18)\n    at Evaluator.visitBlock (/var/www/gamejolt/node_modules/stylus/lib/visitor/evaluator.js:706:39)\n    at Evaluator.Visitor.visit (/var/www/gamejolt/node_modules/stylus/lib/visitor/index.js:28:40)\n    at Evaluator.visit (/var/www/gamejolt/node_modules/stylus/lib/visitor/evaluator.js:156:18)\n    at Evaluator.visitIf (/var/www/gamejolt/node_modules/stylus/lib/visitor/evaluator.js:789:18)\n    at Evaluator.Visitor.visit (/var/www/gamejolt/node_modules/stylus/lib/visitor/index.js:28:40)\n    at Evaluator.visit (/var/www/gamejolt/node_modules/stylus/lib/visitor/evaluator.js:156:18)\n    at Evaluator.visitBlock (/var/www/gamejolt/node_modules/stylus/lib/visitor/evaluator.js:706:39)',
  showStack: false,
  showProperties: true,
  plugin: 'gulp-stylus' }
[20:19:34] Finished 'html2js:tooltip' after 534 ms
[20:19:34] Finished 'html2js:auth:partials' after 510 ms
[20:19:34] Finished 'html2js:modal' after 519 ms
[20:19:34] Finished 'html2js:app:partials' after 559 ms
```

**Comment by hworld** [comment]
Hmmm, did you call `bower i` to install bower components before running gulp?

**Comment by hworld** [comment]
Closing since no info after initial post.
